### ISSUE TITLE
License is not updated

### ISSUE THREAD

**Issue by paodb** [FlowingCode/fc-whatsapp-button#5]
If you go to the LICENSE file in the repository it shows MIT which is the license of the original component we forked. Should it be updated to Apache 2.0? Also the license headers are missing.

**Comment by javier-godoy** [comment]
Changes to the license must be approved by @mlopezFC 
After that, we can proceed with the PR

**Comment by mlopezFC** [comment]
FWIK changing the license from MIT -> Apache 2.0 is a compatible change, so let's change it.

**Comment by javier-godoy** [comment]
> FWIK changing the license from MIT -> Apache 2.0 is a compatible change, so let's change it.

Yes. We already have [other case](https://github.com/FlowingCode/CarouselAddon/blob/50e07c48d7d4628b519b18ab2970f853a8ed1af2/src/main/resources/META-INF/resources/frontend/paper-slider/l2t-paper-slider.js#L1-L25) where we took MIT-licensed code, and developed a derivative work which is licensed under Apache v2. In this case we had forked the repository but we never updated the license information.
